### PR TITLE
Fix a few build warnings

### LINKED ISSUE #45: const cl_type get() type qualifiers warning
When compiling with this parameters `-Wall -Wextra -std=c++11 -O2 -Os -s -DNDEBUG`, I got 

> cl2.hpp:1829:5: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
>      const cl_type get() const { return object_; }

### PR DESCRIPTION
**Pull request by kpet**
- Remove a couple of unused variables
- Remove ignored qualifier on a return type

Fixes #45

Signed-off-by: Kevin Petit <kevin.petit@arm.com>

### CODE REVIEW

File: include/CL/cl2.hpp [hunk 1]
```diff
@@ -1803,7 +1803,7 @@ class Wrapper
 
     cl_type& operator ()() { return object_; }
 
-    const cl_type get() const { return object_; }
+    cl_type get() const { return object_; }
```
Comment (bashbaug) [inline include/CL/cl2.hpp]: I think this is OK - since the wrapper class wraps OpenCL handles it's always OK to return a copy of the handle by value even when the wrapper object is "const".  After this change though, do we need both this function and the non-const overload below, or can the non-const overload be removed?

Comment (kpet) [reply include/CL/cl2.hpp]: Good catch, I can't think of a good reason to keep the non-const overload, I'll remove it.

**Comment by jrprice** [comment]
LGTM 👍

**Comment by bashbaug** [comment]
Great, thanks!  Merging.
